@startuml TareaArchivo

actor Usuario
participant "TareaArchivo" as TareaArchivo
participant "CustomFileClass" as File
participant "Tarea" as Tarea

Usuario -> TareaArchivo : guardarTarea(tarea)
activate TareaArchivo
TareaArchivo -> File : abrir archivo
File --> TareaArchivo : Archivo abierto
TareaArchivo -> File : escribir a archivo
File --> TareaArchivo : Datos escritos
TareaArchivo -> File : close()
File --> TareaArchivo : Archivo cerrado
deactivate TareaArchivo

Usuario -> TareaArchivo : eliminarTarea(id)
activate TareaArchivo
TareaArchivo -> TareaArchivo : cargarTarea(id)
TareaArchivo -> Tarea : Modificar tarea
TareaArchivo -> TareaArchivo : guardarTarea(tarea)
deactivate TareaArchivo

@enduml
